### ISSUE TITLE
Fehlerhafte Verlinkung AP T1: Angebotsvergleich

### ISSUE THREAD

**Issue by danielkaramyshev** [LNA-DEV/Fachinformatiker-Pruefungsvorbereitung#126]
Auf dieser Seite gehen die Verlinkungen zur Bezugskalkulation & Nutzwertanalyse nicht:
href=".Bezugskalkulation.md" führt -> ../wirtschaft/**angebotsvergleich**/Bezugskalkulation.md
href="..bezugskalkulation" führt zur richtigen Datei.

Im Markdown Editor funktioniert es, aber im Web nicht mehr.

**Comment by LNA-DEV** [comment]
@danielkaramyshev Danke für deinen Commit. Schaut sehr gut aus. Ist gleich Live :+1:
