### ISSUE TITLE
USV Beispiel unklar

### ISSUE THREAD

**Issue by danielkaramyshev** [LNA-DEV/Fachinformatiker-Pruefungsvorbereitung#130]
Hi,

mir scheint so, dass das Beispiel von der USV Seite nicht ganz korrekt ist, bzw. Werte aus der Luft gegriffen werden.

Konkret geht es um folgende Zeile:
`Scheinleistung = 700W / 0,6 = 1166,66`
Da wird durch 0,6 geteilt, um von der Wirkleistung in die Scheinleistung umzurechnen. Die 0,6 ist aber nirgends angegeben als Umrechnungsfaktor.

Auch bei den IHK-Prüfungen & Internetaufgaben, die ich bisher gesehen/gefunden habe, steht immer ein Umrechnungsfaktor dabei oder wird erst gar nicht gebraucht. Ist da auch klar, da wir nicht wissen können, wie hoch die Blindleistung jeweils ist.

Sehe ich das richtig, oder übersehe ich etwas?

**Comment by LNA-DEV** [comment]
@danielkaramyshev Rein logisch schaut deine Lösung besser aus. Ich merge mal. Danke für deine Hilfe :smile:

**Comment by danielkaramyshev** [comment]
Gerne :)

**Comment by LNA-DEV** [comment]
Ist Live
